Update
Arkshine/discourse-chat-sidebar pull request #1
Opened 2024-03-11 16:38 UTC by Justman100

2024-03-11 16:38 UTC, Justman100 commented
@Arkshine

2024-03-11 16:45 UTC, Arkshine requested changes
Thanks!

2024-03-11 16:45 UTC, Arkshine commented on locales/de.yml
> +en:
I believe this should be `de` here.

2024-03-13 18:51 UTC, Justman100 commented on locales/de.yml
> +en:
Fixed

2024-03-14 20:10 UTC, Arkshine approved these changes

2024-03-14 20:14 UTC, merged